import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'var(--background)',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'var(--primary)', foreground: 'var(--on-primary)' },
        secondary: { DEFAULT: 'var(--secondary)', foreground: 'var(--on-secondary)' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        success: { DEFAULT: 'hsl(var(--success))', foreground: 'hsl(var(--success-foreground))' },
        
        "error-container": "var(--error-container)",
        "surface-tint": "var(--surface-tint)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "on-background": "var(--on-background)",
        "surface-container-high": "var(--surface-container-high)",
        "surface-container": "var(--surface-container)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "surface-dim": "var(--surface-dim)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "primary-container": "var(--primary-container)",
        "surface": "var(--surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "on-primary-container": "var(--on-primary-container)",
        "on-primary": "var(--on-primary)",
        "on-tertiary": "var(--on-tertiary)",
        "on-surface": "var(--on-surface)",
        "secondary-fixed": "var(--secondary-fixed)",
        "surface-container-highest": "var(--surface-container-highest)",
        "outline": "var(--outline)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-bright": "var(--surface-bright)",
        "on-secondary-container": "var(--on-secondary-container)",
        "tertiary": "var(--tertiary)",
        "on-secondary": "var(--on-secondary)",
        "inverse-surface": "var(--inverse-surface)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "inverse-primary": "var(--inverse-primary)",
        "error": "var(--error)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-variant": "var(--surface-variant)",
        "surface-container-low": "var(--surface-container-low)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-error-container": "var(--on-error-container)",
        "on-error": "var(--on-error)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "outline-variant": "var(--outline-variant)",
        "secondary-container": "var(--secondary-container)",
        "primary-fixed": "var(--primary-fixed)"
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'ui-sans-serif', 'system-ui'],
        mono: ['"IBM Plex Mono"', 'ui-monospace'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'grid-drift': {
          '0%': { transform: 'translateY(0px) translateX(0px)' },
          '50%': { transform: 'translateY(-20px) translateX(10px)' },
          '100%': { transform: 'translateY(0px) translateX(0px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'marker-pulse': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.4)', opacity: '0.4' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 12px rgba(245,158,11,0.3)' },
          '50%': { boxShadow: '0 0 28px rgba(245,158,11,0.7)' },
        },
        'truck-drive': {
          '0%': { transform: 'translateX(-120px)' },
          '100%': { transform: 'translateX(calc(100vw + 120px))' },
        },
      },
      animation: {
        'grid-drift': 'grid-drift 12s ease-in-out infinite',
        shimmer: 'shimmer 1.8s linear infinite',
        'marker-pulse': 'marker-pulse 2s ease-in-out infinite',
        'fade-up': 'fade-up 0.5s ease-out forwards',
        blink: 'blink 1s step-end infinite',
        'glow-pulse': 'glow-pulse 2.5s ease-in-out infinite',
        'truck-drive': 'truck-drive 3s linear infinite',
      },
    },
  },
  plugins: [],
}
export default config
